# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = '''$character$all[ # ](bold green)'''

[character]
success_symbol = '[ ](bold green)'
error_symbol = '[ ](bold red)'
vimcmd_symbol = '[ ](bold green)'

[cmd_duration]
disabled = true

[directory]
style = 'bold blue'

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style) '

[git_status]
style = 'red'

[php]
disabled = true

[package]
disabled = true

[line_break]
disabled = true

